config/routes.rb
Rails.application.routes.draw do
  resources :sessions
  resources :users

  get 'welcome/index'
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  root 'welcome#index'
  resources :articles
  resources :categories

end

app/models/article.rb
class Article < ActiveRecord::Base
    belongs_to :user
    has_many :article_categories
    has_many :categories, through: :article_categories
    
    validates_presence_of :title
    validates_presence_of :content
    validates_presence_of :categories

end

app/models/article_category.rb
class ArticleCategory < ActiveRecord::Base
	belongs_to :article
	belongs_to :category
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :article_categories
	has_many :articles, through: :article_categories

	validates :name, uniqueness: true
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
	has_many :articles
	validates_uniqueness_of :email
	validates :name, presence: true
	validates :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :get_categories

  def get_categories
  	@categories = Category.all.order(:name)
  end

  def authorize
    redirect_to login_url, alert: "You must be logged in to view this page." if current_user.nil?
  end

  private
  def current_user
  	@current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	before_filter :authorize, only: [:new]

	def index
		@articles = Article.order(updated_at: :desc).limit(25)
	end

	def show
		@article = Article.find(params[:id])
	end

	def new
		@article = Article.new
	end

	def create
		@article = Article.new(article_params)
		if @article.save
			redirect_to @article
		else
			render "new"
		end
	end

	def update

	end

	def destory

	end

    def show_categories
    	self.categories.each do |category|
            print category.name
    		if category.id != self.categories.last.id
    			print " / "
    		end
    	end
    end

	private
		def article_params
			params.require(:article).permit(:title, :content, :category_ids => [])
		end


end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
	def index
		@categories = Category.order(name: :desc).limit(25)
	end

	def show
		@category = Category.find(params[:id])
	end

	def new
		@article = Article.new
	end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new

  end

  def create
  	user = User.find_by_email(params[:email])
  	if user && user.authenticate(params[:password]) # get this for free from has_secure_password
  		session[:user_id] = user.id
  		redirect_to root_url, notice: "Welcome back, " + user.name
  	else
  		flash.now.alert = "Invalid email/password combination."
  		render "new"
  	end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "You have successfully logged out."
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

 def new
   @user = User.new
 end

 def create
   @user = User.new(user_params)
   if @user.save
   	 session[:user_id] = @user.id
     redirect_to root_url, notice: "Thank you for signing up"
   else
     render "new"
   end
 end

 private 
   def user_params
     params.require(:user).permit(:email, :name, :password, :password_confirmation)
   end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
		@recent_articles = Article.order(updated_at: :desc).limit(5)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<%= form_for @article do |f| %>
	<div class="control-group">
		<%= f.label :title %>
		<div class="controls">
			<%= f.text_field :title %>
		</div>
	</div>
	<div class="control-group">
		<%= f.label :content %>
		<div class="controls">
			<%= f.text_area :content, rows: "20", cols: "100" %>
		</div>
	</div>

	<div class="category-control">
		<%= f.label 'File under at least one category' %>
		<% Category.all.order(name: :asc).each do |category| %>
			<div>
				<%= check_box_tag "article[category_ids][]", category.id %>
				<%= category.name %>
			</div>
		<% end %>
	</div>

	<div class="form-actions">
		<%= f.submit nil %>
		<%= link_to("Cancel", articles_path) %>
	</div>
<% end %>

app/views/articles/edit.html.erb
<%- model_class = Article -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/articles/index.html.erb
<% # Articles Index View: articles/index.html.erb %>

<h1>This is the Index View for Articles</h1>

<% @articles.each do |article| %>
	<div>
		<p class="text-info"><% article.categories.each do |category| %>
              <%= link_to category.name, category %>&nbsp;
              <% if category.id != article.categories.last.id %>
					<%= " / " %>
			  <% end %>
            <% end %>
		</p>
		<h3><%= link_to article.title, article %></h3>
		<p class="text-info">Published on <%= article.created_at.strftime('%b %d, %Y') %></p>
		<p><%= truncate(article.content, length:200) %></p>
	</div>
<% end %>

app/views/articles/show.html.erb
<% # Articles Show View: articles/show.html.erb %>

<div class="text-info">
	<% @article.categories.each do |category| %>
		<%= link_to category.name, category %>
		<% if category.id != @article.categories.last.id %>
			&nbsp;/&nbsp;
		<% end %>
	<% end %>
</div>

<h1><%= @article.title %></h1>

<p class="text-info">Published: <%= @article.created_at.strftime('%b %d, %Y') %> |
	Last update: <%= @article.updated_at.strftime('%b %d, %Y') %>
</p>

<p><%= @article.content %></p>

app/views/categories/index.html.erb
<% # Categories Index View: categories/index.html.erb %>

<h1>This is the Index View for Categories</h1>

<% @categories.each do |category| %>
	<div>
		<h3><%= link_to category.name, category %>
			(<%= category.articles.count %> Articles)
		</h3>
	</div>
<% end %>

app/views/categories/show.html.erb
<% # Category Show View: categories/show.html.erb %>

<h1><%= @category.name %></h1>

<% @category.articles.order(title: :asc).each do |article| %>
	<div>
		<h3><%= link_to article.title, article %></h3>
		<p class="text-info">Published on <%= article.created_at.strftime('%b %d, %Y') %></p>
		<p><%= truncate(article.content, length:200) %></p>
	</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Wikiful</title>
	<!--[if lt IE 9]>
		<script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
	<![endif]-->
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>
</head>
<body>
	<div class="navbar navbar-fixed-top navbar-default">
	 <div class="navbar-inner">
	   <div class="container">
	     <%= link_to "Wikiful", root_path, :class => "navbar-brand" %>
	     <div class='session-controls navbar-text pull-right'>
	     	<% if current_user %>
	     		Logged in as <%= current_user.name %>
	     		<%= link_to "Log Out", logout_path, :class => "btn btn-primary btn-sm" %>
	     	<% else %>
				<div class="btn-group">
					<%= link_to "Sign Up", signup_path, :class => "btn btn-default" %>
					<%= link_to "Log In", login_path, :class => "btn btn-default" %>
				</div>
	        <% end %>
	      </div>
	   </div>
	 </div>
	</div>

	<div class="container">
		<div class="row">
			<div class="col-sm-4 flash-message">
				<% flash.each do | name, msg | %>
					<%= content_tag :div, msg, id: "flash_#{name}", :class => "alert alert-info" %>
				<% end %>
			</div>
		</div>
		<div class="row">
			<div class="col-sm-9 main-content"><%= yield %></div>
			<div class="col-sm-3 sidebar">
				<div class="my-wiki-site">
					<h4>My Wikiful</h4>
					<div class="list-group">
				    	<%= link_to "Write a Wiki", new_article_path, :class => "list-group-item" %></li>
					</div>
				</div>
				<div class="categories-sidebar">
					<h4>Categories</h4>
					<div class="list-group">
				    	<% @categories.each do |category| %>
							<% category_nav_class = "list-group-item" # create a category_nav_class with the generic class %>
				    		<% if @category.present? # if this is a category page %>
				    			<% if @category.name == category.name # if the name of this category page is the name of this category in the @categories list %>
				    				<% category_nav_class += " active" # add an 'active' class to category_nav_class %>
				    			<% end %>
				    		<% end %>
				    		<% # And finally actually make the link, giving a "badge" with the number of articles in each category %>
				    		<%= link_to category, :class => category_nav_class do %>
				    			<%= category.name %> <span class="badge"><%= category.articles.count.to_s %></span>
				    		<% end %>
				    	<% end %>
					</div>
				</div>
				<div class="about">
					<h4>About Wikiful</h4>
					<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusantium architecto earum neque perspiciatis quia animi debitis quod repellat vitae explicabo. Sapiente aliquam reprehenderit id vitae atque ducimus facere molestias soluta?</p>
				</div>
			</div>
		</div>
   </div>


</body>
</html>

app/views/users/new.html.erb
<% # Users New View: users/new.html.erb %>

<h1>Sign Up</h1>

<% if @user.errors.any? %>
	<div class="error-message bg-warning text-danger">
		<h2>Oops! There was a problem...</h2>
		<ul>
			<% @user.errors.full_messages.each do |message| %>
				<li><%= message %></li>
			<% end %>
		</ul>
	</div>
<% end %>
<%= form_for @user do |f| %>
 <div class='field'>
   <%= f.label :name %>
   <%= f.text_field :name %> 
 </div>
 <div class='field'>
   <%= f.label :email %>
   <%= f.text_field :email %> 
 </div>
 <div class='field'>
   <%= f.label :password %>
   <%= f.password_field :password %> 
 </div>
 <div class='field'>
   <%= f.label :password_confirmation %>
   <%= f.password_field :password_confirmation %> 
 </div>
 <div class="actions"><%= f.submit %></div>
<% end %>

app/views/welcome/index.html.erb
<h1>Welcome to Wikiful</h1>
<p>Here are some recent articles:</p>

<% @recent_articles.each do |article| %>
	<div>
		<h3><%= link_to article.title, article %></h3>
		<p class="text-info"><% article.categories.each do |category| %>
              <%= link_to category.name, category %>
              <% if category.id != article.categories.last.id %>
					<%= " / " %>
			  <% end %>
            <% end %>
			- Published on <%= article.created_at.strftime('%b %d, %Y') %>
		</p>
		<p><%= truncate(article.content, length:100) %></p>
	</div>
<% end %>